### ISSUE TITLE
Form to add new Activities

### ISSUE THREAD

**Issue by Manu7864z** [Manu7864z/capstone-project#1]
## List of Activities

As an User
I want a Form and a submit button
So that i can choose date and time and submit a new activity

## Description

- Input field and Submit Button
- field to choose time and date

## Acceptance criteria

- [ ] empty Entries should not be able to submit
- [ ] user can choose time and date
- [ ] Entries with all needed information can be submitted and form refreshes

## Tasks

- [ ] Form with input field for activity
- [ ] field to choose a date 
- [ ] field to choose a time
- [ ] checkbox for good or bad weather activity
- [ ] Submit Button 

![User-Stories](https://user-images.githubusercontent.com/120590219/222729814-cc53d554-b60b-49d8-942a-238fa8bd939c.png)

**Comment by MelissaDuve** [comment]
nice US :) the title of your user story should be something like "List of Activities" and not User-Story 1
