### ISSUE TITLE
User experience

### ISSUE THREAD

**Issue by Manu7864z** [Manu7864z/capstone-project#10]
##  

As an User
I want an application that is easy to use 
So that i know where i can find everything and 
use it correctly

## Description

- add more hints for users 
- add more info

## Acceptance criteria
- [x] more info in the about page
- [x] a message when submitted correctly
- [x] forecast for the next 3 days 

## Tasks

- [x] control the input fields
- [x] add a submit message
- [x] get some more api date on the home page
- [x] add About page info
