### ISSUE TITLE
User Interface

### ISSUE THREAD

**Issue by Manu7864z** [Manu7864z/capstone-project#11]
## User interface 

As an User
I want a styled application
So that i feel good and like to use the app 

## Description

- global styling 
- choose the colors i want to use

## Acceptance criteria

- [x] vars for colors
- [x] vars for border radius etc. 
- [x] all elements are styled
- [x] new created elements are styled

## Tasks

- [x] choose colors and some lighter and 
darker variations
- [x] choose vars for reusable color, border radius 
- [x] style components 
- [x] style all elements

**Comment by TuncAlt** [comment]
NICE WORK!
