### ISSUE TITLE
Starting Page

### ISSUE THREAD

**Issue by Manu7864z** [Manu7864z/capstone-project#18]
## Starting Page

As an User
I want a start screen  
So that the data is loaded when i got to the 
homepage 

## Description

- new Page
- after 3 seconds the user is pushed to homepage

## Acceptance criteria

- [x] new page
- [x] first page the user is seeing 
- [x] after 3 seconds he gets redirected to Homepage
- [x] a good styling

## Tasks

- [x] add new page
- [x] change the routes
- [x] use a lottiefile to add something nice
- [x] style the loading div 

## Complexity
S
