### ISSUE TITLE
List with filter, edit and delete function

### ISSUE THREAD

**Issue by Manu7864z** [Manu7864z/capstone-project#2]
## User Story 2

As an User
I want a List with plannend activities and Buttons
So that i can see all possible activities, create new, delete and edit them

## Description

- edit Button
- List of all activities
- delete Button

## Acceptance criteria

- [x] List should display all possible activities 
- [x] all Listitems should have an edit button
- [x] clicking the edit button should open a form to edit
- [x] all li have a delete Button
- [x] clicking the delete Button should delete the li 

## Tasks

- [x] delete button on every li and function 
- [x] edit button on every li and function
- [x] render a dynamic list which contains the data from the form 

![User-Story-2](https://user-images.githubusercontent.com/120590219/222758078-44bf94ea-1656-40f6-bb7f-d2d1c677a5a5.png)

**Comment by TuncAlt** [comment]
maybe you should put your img in description
