### ISSUE TITLE
Accessability

### ISSUE THREAD

**Issue by Manu7864z** [Manu7864z/capstone-project#21]
## Accessability

As an User
I want an Application that is accessable for everyone
So that it can be used by people with disabilities

## Description

- aria labels for HTML tags
- try to get an as good as possible lighthouse score 
for accessability

## Acceptance criteria

- [x] aria labels for all tags
- [x] code works still as desired
- [x] lighthouse score at least 80 or more

## Tasks

- [x] add labels to tags
- [x] test in lighthouse and adjust my code

## Complexity
 S
