### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by Manu7864z** [Manu7864z/capstone-project#23]
## Testing

As a Developer
I want an Application that includes test 
So that my code is tested & still working 
after updates of programs or libaries 

## Description

- writing test for components

## Acceptance criteria

- [x] 3 components test working 

## Tasks

- [x] write automated test for at least 3 components
- [x] read the documentation of testing session

## Complexity

M
