### ISSUE TITLE
Homepage and functions

### ISSUE THREAD

**Issue by Manu7864z** [Manu7864z/capstone-project#5]
## User Story 3

As an User
I want a homePage with a List filtered regarding 
the choosen date and the current weather
So that i can see plannend activities and weather 
condition

## Description
![Homepage US](https://user-images.githubusercontent.com/120590219/223992707-ef519faf-c5b2-467b-8aa9-1064b526f656.png)

- new page 
- Header which appears on all Pages
- filter activities Array 
- fetch Api data and render relevant info

## Acceptance criteria

- [ ] header showing and title
- [ ] open a calendar and choose a date
- [ ] filter List by date
- [ ] Data changes on date (temp. conditon..) 
- [ ] List with checkboxes, if cklicked Activities 
should be removed

## Tasks

- [ ] create header and append on the root
- [ ] fetch api data 
- [ ] render api data (temp. condition ...) 
- [ ] implement button, when cklicked render Calendar
- [ ] filter Array List on current date /state
- [ ] render filtered List 
- [ ] append checkboxes
- [ ] checkbox cklicked = deleted
