### ISSUE TITLE
PersonalPage and Navbar

### ISSUE THREAD

**Issue by Manu7864z** [Manu7864z/capstone-project#6]
## personal Page

As an User
I want a page for personal information 
(location, name..) and a navbar
So that i can change my location and 
personal Information and switch to other pages

## Description
![PersonalPage](https://user-images.githubusercontent.com/120590219/223997588-b1b68956-aed6-48f6-962c-788d2a3bf6af.png)

- new page 
- Heading Personal Information
- adding name, Location etc. 
- adding a navbar 

## Acceptance criteria

- [x] able to add your name
- [x] set your location
- [x] edit your name and location 
- [x] able to switch to the other pages

## Tasks

- [x] Heading Heading Personal Information
- [x] input field to add your name
- [x] input to set Location
- [x] create navbar which appears on all pages
- [x] create links in the navbar

**Comment by Marcel-FR** [comment]
Looks good!
